### PR TITLE
fix: fixed M_02

### PR DESCRIPTION
**Pull request by ThomasPiellard**

### CODE REVIEW

**Comment by 0xmpeter** [comment]
Hi @ThomasPiellard, we had a look at the fix but it doesn't seem to address the issue. Specifically, we still see three main problems with it:
- `u` does not depend on `v`, `[Wz]1` and `[Wzω]1` as we recommended.
- The fix derives `u` by hashing **pointers**, not the actual values in memory/calldata.
- `u` is not reduced, and thus is not guaranteed to be an element of the field.

We are still able to forge false proofs with the same method. If it helps, here is a suggestion for a computation of u that we believe would fix the issue:

```
function batch_verify_multi_points(aproof) {
	let state := mload(0x40)
	let mPtr := add(state, state_last_mem)

	// Derive a random number. As there is no random generator, we
	// do an FS like challenge derivation depending on the transcript 
	// following round 5 of the PLONK prover

	mstore(mPtr, mload(add(state, state_gamma_kzg))) // mPtr[0x00:0x20] <- v
	mstore(add(mPtr, 0x20), calldataload(add(aproof, proof_batch_opening_at_zeta_x))) // mPtr[0x20:0x60] <- [Wz]1
	mstore(add(mPtr, 0x40), calldataload(add(aproof, proof_batch_opening_at_zeta_y)))
	mstore(add(mPtr, 0x60), calldataload(add(aproof, proof_opening_at_zeta_omega_x))) // mPtr[0x60:0xa0] <- [W𝑧ω]1
	mstore(add(mPtr, 0x80), calldataload(add(aproof, proof_opening_at_zeta_omega_y)))

	let random := staticcall(gas(), 0x2, mPtr, 0xa0, mPtr, 0x20) // mPtr[0x00:0x20] <- SHA256(mPtr[0x00:0xa0])
	if iszero(random){
		error_random_generation()
	}
	random := mod(mload(mPtr), r_mod) // Variable reused to avoid stack-too-deep error

	[...]
```

This suggestion would have to be validated and end-to-end tested on your end to ensure that it does not introduce new issues.

**Comment by ThomasPiellard** [comment]
So I reduced u and now it depends on the values as intended.

In the following I use the word 'transcript' as if it were a FS transformation, even though here nothing is interactive and the purpose is to derive a randomness depending on some sensitive data.

For the dependancy of u, to me at this stage (that is batch verifying the 2 proofs at 2 points, z and zω, of 2 digests, [Z] and [folded_digests_to_open_at_z] ) the protocol is encapsulated and the transcript consists of the context of the protocol itself, so the transcript is {z, zω, [Z],  [folded_digests_to_open_at_z], [batch_opening_proof_at_z], [opening_proof_at_ zω]). I included everything, except  zω which is redundant with z (since ω is a public constant). The dependancy of u on v is guaranteed since [folded_digests_to_open_at_z], which has been constructed using v, is part of the transcript. Does this address the attack ?

**Comment by 0xmpeter** [comment]
It should, but in [these lines](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R726-R731) the `mload` should be replaced by a `calldataload` as these values are read from the proof in calldata, not from memory otherwise you're reading unrelated memory slots. 

Also, it doesn't change anything but:
- Index 0x60 is skipped by going [directly from 0x40 to 0x80](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R726-R727)
- I think the code would be cleaner if the [`mod`](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-0d6fde626966419f147f546ad12d67dcd479aae9459210fabc0c37dae32ecec0R733) was after the error like in the fix we suggested, with `random := mod(mload(mPtr), r_mod)`. As it stands, you would raise an error if the hash is a multiple of `r_mod`, which wont happen in practice but could be avoided anyway 🙂

**Comment by ThomasPiellard** [comment]
One other thing: the derivation of u is based on [folded_digests_to_open_at_z], which is not a 1 to 1 function in v... In fact [folded_digests_to_open_at_z] is something like ∑ᵢ vⁱ [Pᵢ], with say n points, so it is a n to 1 function at most (from Fr to Fr) this time. So u is derived using hash(f(v), ... ) where f is n to 1. However v is uniquely derived from each individual challenges which were folded in the previous step. Do you think there is an attack from this ? I will add it to the transcript for the derivation of u just in case. For z(zω) I can add it as well (for the derivation of v) in fact, I will modify the kzg api from gnark-crypto, we'll be sure then that there is no issue. I will do that tomorrow if that's ok for you

**Comment by 0xmpeter** [comment]
Thank you Thomas, the fix is definitely improving but there is still one important issue with it: [`add(state, state_folded_digests_x)`](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R724) and other lines referring to the `state` variable give out memory pointers, and the code switched to calling `calldataload` on them. However, these pointers point to memory, not calldata. Lines [724, 725](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R724-R725) and [732](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R732) need to use `mload` instead of `calldataload`, but the rest of the lines are correct as `aproof` is a pointer to calldata.

A tiny detail is that when adding `z(zw)` to the computation of `v`, the size was increased from 0x16 to 0x17 but a [comment](https://github.com/Consensys/linea-contracts-fix/pull/30/files#diff-adc296b28efd3378c50e9b3c494e3d209dd22a953ca9b7cf13c59f4ed73431e5R926) still refers to 0x16. 

Otherwise the fix looks good to me ! 🙂 

> I will add it to the transcript for the derivation of u just in case

I think that's the right approach, adding an additional item to be hashed doesn't cost much in terms of gas and it's better to be safe than sorry.

**Comment by ThomasPiellard** [comment]
ok sorry for the silly mistakes, it's fixed normally

**Comment by 0xmpeter** [comment]
Looks good to me ! Thank you Thomas

**Review by thedarkjester — APPROVED** [review]

**Pull request merged**
